version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: tcc
      MYSQL_USER: tcc
      MYSQL_PASSWORD: tcc_password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
