export const seedData = [
  {
    name: 'Uber',
    logo:
      'https://media.licdn.com/dms/image/C4D0BAQFiYnR1Mbtxdg/company-logo_400_400/0?e=1577318400&v=beta&t=ouxkvEkvLnWXOHY-gtEaUUf7tnO_DWy17C7IgVnG7vI',
    address: '120 Lynn Williams Street',
    city: 'Toronto',
    province: 'ON',
    country: 'Canada',
    zipCode: 'M6K 3R6',
    industry: 'Internet',
    size: '10,001+ employees',
    founded: 2009,
    description:
      'At Uber, we ignite opportunity by setting the world in motion. We take on big problems to help drivers, riders, delivery partners, and eaters get moving in more than 600 cities around the world.',
    email: 'hr@uber.com',
    tel: '555-555-0001',
    website: 'https://www.uber.com',
    facebook: 'https://www.facebook.com/UberCanada/',
    linkedin: 'https://www.linkedin.com/company/uber-com/',
    location: {
      lat: 43.6390608,
      lng: -79.4199211,
    },
  },
  {
    name: 'Drop',
    logo:
      'https://media.licdn.com/dms/image/C4E0BAQEyBAZxI479Jw/company-logo_400_400/0?e=1577318400&v=beta&t=QryW4RTJa1UHKqayBf0Kqxneqt6FScVyJYedsbOUsNs',
    address: '120 Front St E',
    city: 'Toronto',
    province: 'ON',
    country: 'Canada',
    zipCode: 'M5A 4L9',
    industry: 'Consumer Services',
    size: '51-200 employees',
    founded: 2015,
    description:
      'At Drop, we’re on a mission to level-up consumer lives, one reward at a time. Through our personalized commerce platform, we intelligently surface the right brands, at the right time, to make our members’ every day a level better than it was before.  Powered by machine learning, we match consumers with our over 300+ partner brands to satisfy two main goals: to earn points from their purchases and redeem them for instant rewards. Calling Toronto home but operating under a global mindset, Drop is building the next level experience for our 3 million+ members across North America, and most recently, the UK.',
    email: 'hr@joindrop.com',
    tel: '555-555-0002',
    website: 'https://www.joindrop.com',
    linkedin: 'https://www.linkedin.com/company/joindrop/',
    location: {
      lat: 43.6502362,
      lng: -79.3720105,
    },
  },
  {
    name: 'Archon Systems',
    logo: 'https://inflowinventory.cachefly.net/archonWebsite/images/logo_grey_b.png',
    address: '260 Carlaw Ave, Unit 207, Toronto M4M 3L1',
    city: 'Toronto',
    province: 'ON',
    country: 'Canada',
    zipCode: 'M4M 3L1',
    industry: 'Computer Hardware & Software',
    size: '1 to 50 employees',
    founded: 2005,
    description: 'Archon Systems',
    email: 'info@archonsystems.com',
    tel: '866-923-4974',
    website: 'https://www.archonsystems.com',
    linkedin: '',
    location: {
      lat: 43.6629692,
      lng: -79.3432509,
    },
  },
  {
    name: 'Canvass Analytics',
    logo:
      'https://static.wixstatic.com/media/0a64fb_48714e00a0f841c28caa7802556a0569~mv2.jpg/v1/fill/w_233,h_31,al_c,q_80,usm_0.66_1.00_0.01/Canvass%20Logo%20RGB.webp',
    address: '325 Front St W, Toronto M5V 2Y1',
    city: 'Toronto',
    province: 'ON',
    country: 'Canada',
    zipCode: 'M5V 2Y1',
    industry: 'Computer Hardware & Software',
    size: '1 to 50 employees',
    founded: 2017,
    description: 'Canvass Analytics',
    email: 'info@canvass.io',
    tel: '',
    website: 'https://www.canvass.io/',
    linkedin: '',
    location: {
      lat: 43.6431718,
      lng: -79.3924795,
    },
  },
  {
    name: 'Loopio',
    logo:
      'https://static.wixstatic.com/media/0a64fb_48714e00a0f841c28caa7802556a0569~mv2.jpg/v1/fill/w_233,h_31,al_c,q_80,usm_0.66_1.00_0.01/Canvass%20Logo%20RGB.webp',
    address: '310 Spadina Avenue, Suite 600 Toronto, ON M5T 2E8',
    city: 'Toronto',
    province: 'ON',
    country: 'Canada',
    zipCode: 'M5T 2E8',
    industry: 'Enterprise Software & Network Solutions',
    size: '51 to 200 employees',
    founded: 2014,
    description:
      'At Loopio, our mission is to streamline the way organizations respond to Requests for Proposals (RFPs), Due Diligence Questionnaires (DDQs), and Security Questionnaires. We help companies across several industries collaborate more intelligently on a platform that embodies simplicity and an exceptional user experience.',
    email: 'info@canvass.io',
    tel: '844-456-6746',
    website: 'https://www.loopio.com/',
    linkedin: '',
    location: {
      lat: 43.653449,
      lng: -79.4006702,
    },
  },
];
